
spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/market
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
#jwt
fruit.jwt.password: fruitKey
vegetable.jwt.password: vegetableKey
